# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c4fe406c477281f60f55d67a7ac04ff2db9aa060470ce388f3b9733944427abbb5ef20edb1a27f48d0bf62eec28b618de6149170cdb183ecc494e911393dbb4e

test:
  secret_key_base: c208a5317dbc1ba92c8b01f37864d2c374d9706d4b62373470de37117d63f7cc84d8f385f4bafccfe713279cd8d2549c8b6444082c47992410428842be1162db

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
